### ISSUE TITLE
Title sorting for Episodes (Shows)

### ISSUE THREAD

**Issue by Veepas** [adamgot/python-plexlibrary#43]
Hello there,

first of hands down this project is awesome i absolutely love it!

I tried to implement the following Trakt List:
https://trakt.tv/users/donxy/lists/arrowverse

It is sorted by episode number like  1. ArrowE01S01 - 2. ArrowS01E02 - 3. TheFlashS01E01 - 4. ArrowS01E03

I have sorted on and sort by {number}. {title}
I would have wanted it to be sorted like above but instead it just puts it like this:

1. Arrow(full) - 2. TheFlash(full)

Is there another possible syntax to get the wanted result ?

Thanks in advance. Any help or idea is really appreciated!!

Greets

**Comment by adamgot** [comment]
There is a way to do it like you want using just a smart playlist, but this script won’t rename individual episodes.

I’m sure someone has a detailed guide out there using smart playlists and custom filters, but basically you create a custom filter on your tv library selecting only the arrowverse shows, and sorting by air date. From there you click the create playlist button.
