### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by petercris** [adamgot/python-plexlibrary#48]
Is there any way to add it to crontab to run it automatically?

**Comment by adamgot** [comment]
Sure. 

    /path/to/python /path/to/plexlibrary recipe

**Comment by petercris** [comment]
Thanks. It's the first thing I tried and it didn't work for me.

**Comment by adamgot** [comment]
Is cron trying to run the command? What does the syslog say?

**Comment by petercris** [comment]
Jan  3 23:00:01 sd-70132 CRON[2118]: (root) CMD (/usr/bin/python /home/petercris/python-plexlibrary-master/plexlibrary movies_imdb_top_250)
Jan  3 23:00:24 sd-70132 CRON[2117]: (CRON) info (No MTA installed, discarding output)

**Comment by adamgot** [comment]
Pipe the output to a file and see what it says? Could be differences in environment between your user and cron that causes python to crash.

**Comment by petercris** [comment]
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Running the recipe 'movies_imdb_top_250'
Retrieving the trakt list: https://api.trakt.tv/users/justin/lists/imdb-top-rated-movies/items/movies
Trying to match with items from the '1. Pelis' library 
Trying to match with items from the '2. Cine infantil' library 
Trying to match with items from the '1. Pelis Anime' library 
1 The Shawshank Redemption (1994)
2 The Godfather (1972)
3 The Godfather: Part II (1974)
4 The Dark Knight (2008)
5 12 Angry Men (1957)
6 Schindler's List (1993)
7 The Lord of the Rings: The Return of the King (2003)
8 Pulp Fiction (1994)
9 The Good, the Bad and the Ugly (1966)
10 Fight Club (1999)
11 The Lord of the Rings: The Fellowship of the Ring (2001)
12 Forrest Gump (1994)
13 The Empire Strikes Back (1980)
14 Inception (2010)
15 The Lord of the Rings: The Two Towers (2002)
16 One Flew Over the Cuckoo's Nest (1975)
17 GoodFellas (1990)
18 The Matrix (1999)
19 Seven Samurai (1954)
20 City of God (2002)
21 Se7en (1995)
22 Star Wars (1977)
23 The Silence of the Lambs (1991)
24 It's a Wonderful Life (1946)
25 Life Is Beautiful (1997)
26 The Usual Suspects (1995)
27 Spirited Away (2001)
28 Saving Private Ryan (1998)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/petercris/python-plexlibrary-master/plexlibrary/__main__.py", line 3, in <module>
    main()
  File "/home/petercris/python-plexlibrary-master/plexlibrary/plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "/home/petercris/python-plexlibrary-master/plexlibrary/recipe.py", line 687, in run
    missing_items, list_count = self._run()
  File "/home/petercris/python-plexlibrary-master/plexlibrary/recipe.py", line 161, in _run
    i+1, item['title'], item['year']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)

**Comment by petercris** [comment]
I don't know if it is the correct answer, but I have put these lines in plexlibrary.py and it works well for me:
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by adamgot** [comment]
Set this in your crontab:

    PYTHONIOENCODING=UTF-8

On 4 Jan 2019, at 00:16, petercris <notifications@github.com> wrote:

I don't know if it is the correct answer, but I have put these lines in
plexlibrary.py and it works well for me:
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/adamgot/python-plexlibrary/issues/48#issuecomment-451308543>,
or mute the thread

**Comment by petercris** [comment]
Works perfect! Thanks so much!
