### ISSUE TITLE
Add IMDb and Trakt.tv lists which are not user based

### ISSUE THREAD

**Issue by danz1995** [adamgot/python-plexlibrary#59]
Hey, first thanks a lot for this code. It has been helping a lot to sort through my library!

Just wanted to know, what if we could add lists which are automatically updated by IMDb and Trakt.tv sites? Lists that do not depend on user input and are just automatically updated. This would help a lot to sort through what is trending now, more popular this week and etc. See links as examples:

https://trakt.tv/movies/trending
https://www.imdb.com/chart/boxoffice/
https://trakt.tv/movies/watched/weekly
https://trakt.tv/movies/boxoffice
https://www.imdb.com/chart/moviemeter
https://trakt.tv/movies/popular (if possible for this year)

In addition to that, for sorting, which weights (index, vote... ) and genre_bias I can use?

**Comment by adamgot** [comment]
You definitely already can, check out the examples and [Trakt API documentation](https://trakt.docs.apiary.io/#). IMDB support was also just added by ThomasRules2000.

**Comment by adamgot** [comment]
Not sure what you're asking for regarding the weights. There's index, vote, age, random and genre_bias. The possible genres can be found on TheMovieDB.
