### ISSUE TITLE
Library entries not sorted by {number}

### ISSUE THREAD

**Issue by Loewkie** [adamgot/python-plexlibrary#63]
I just adpated it straight from the IMDB top 250 example, only added my own library names and folders.

`# New library details`
`new_library:`
`  name: '_Movies - IMDB Top 250'`
`  folder: 'D:\Main\RClone\python-plexlibrary-master\symlinks\_Movies - IMDB Top 250'`
`  sort: true`
`  sort_title:`
`    format: '{number}. {title}'`
`    visible: true`
`    absolute: true  # Skips numbers for missing items`
`  # Limit the age (in years) of items to be considered`
`  # * 0 for no limit`
`  max_age: 0`
`  # Maximum number of items to keep in the library`
`  max_count: 250`
`  # Remove items that no longer exist in the source lists`
`  remove_from_library: true`

So if I understand it correctly it should become something like:

1. The Shawshank Redemption
2. The Godfather Part II

However, the sort titles of the Plex items are just the regular titels of the items. So it's just simply sorted alphabetically. Looking at the CMD it does know the actual numbers that belong to the items.

**Comment by boff999** [comment]
Did you manage to fix this?
