### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by xvvjt4** [adamgot/python-plexlibrary#66]
Hey,

i keep getting this error, anyone have any clue what to look into?

This is when running: python plexlibrary -h

![image](https://user-images.githubusercontent.com/57671797/68677097-baa8aa00-055b-11ea-96eb-c3e620ecaea1.png)

**Comment by skuid87** [comment]
I'm getting the exact same issue. Anyone have a resolution to this?

**Comment by skuid87** [comment]
This fixed it for me:

`sudo pip install mock`

**Comment by xvvjt4** [comment]
> This fixed it for me:
> 
> `sudo pip install mock`

Yeah, that worked like a charm for me to!
