### ISSUE TITLE
Support for creating playlists instead of creating new libraries.

### ISSUE THREAD

**Issue by adamgot** [adamgot/python-plexlibrary#8]

**Comment by blacktwin** [comment]
Don't know if you want to add more to this but you can [share playlists with users](https://gist.github.com/JonnyWong16/2607abf0e3431b6f133861bbe1bb694e).

**Comment by adamgot** [comment]
@blacktwin Suspected something like this was possible, thanks for the tip!

**Comment by Hellowlol** [comment]
Just use plexapi playlist.copyToUser('username)

**Comment by adamgot** [comment]
@Hellowlol Thanks. This will just create a copy, right? So for updates I will have to find every copy and update those too.

It seems to be possible to have options to add the playlist to:

- all users
- all users excluding...
- specific users

Just something like...

```python
for user in serverinstance.myPlexAccount().users():
    # check if user is candidate
    # create a server instance for user
    # fetch their playlists
    for playlist in user_server.playlists():
        if playlist.title == playlist_title:  # FIXME: better way to match?
            # edit playlist
            break
    else:
        # create new playlist
        pass
```

**Comment by Hellowlol** [comment]
Yes, it just takes a playlist for user x and creates that playlist on user b

**Comment by Hellowlol** [comment]
I would check vs the title since there can be several playlist with the same title. 

'''[m.title for m in playlist.items]'''

**Comment by Hellowlol** [comment]
Plexapi could use some dunder methods to simplify this for the users.

**Comment by Hellowlol** [comment]
You can create and edit a library to so your Plex class isn't really needed.

**Comment by adamgot** [comment]
@Hellowlol Got it, as well as editing items and setting sortTitle, collections etc.  #20  Thanks!

**Comment by EnorMOZ** [comment]
Seems to be doing something similar but would like to have it added to this.
https://github.com/pbrink231/plex_top_playlists

**Comment by Migz93** [comment]
I'd definitely like this.
I'm finding with the new Plex UIs that getting to other libraries can be a bit of a pain, especially when running multiple servers.
It'd be much easier & neater to have this export them into playlists

**Comment by danialmoghaddam** [comment]
I like the concept of recipes more all other script out there. But totally prefer playlist over library. 
Probably for now, can keep it simple and just create the playlist for the owner. Then more complex functionality would be sharing with other Plex users.

**Comment by Hellowlol** [comment]
Sharing a playlist is easy, you can do that with plexapi

**Comment by danialmoghaddam** [comment]
@Hellowlol ok maybe I didn't explain myself properly. All I wanted to say was, I like to this script (because I like the concept of recipes) but create playlists instead of libraries.

**Comment by adamgot** [comment]
Added courtesy of @nwithan8 

Still missing support for other users https://github.com/adamgot/python-plexlibrary/issues/83
